from pathlib import Path

csvDir             = Path("DITS/class")
txtDir             = Path("DITS/class")
imageDir           = Path("DITS/class/image")
dayTest            = Path("DITS/detection_test/day")
fogTest            = Path("DITS/detection_test/fog")
nightTest          = Path("DITS/detection_test/night")
Test               = Path("DITS/detection_test/test")
imageTest          = Path("image")
modelliDir         = Path("train/modelli")
checkpointsDir     = Path("train/checkpoints")
historiesDir       = Path("train/histories")
graphsDir          = Path("train/graphs")
yoloResult         = Path("image/yolo")
yoloWeights        = Path("/home/marco/progetti/MachineLearning_Unict/yolo_image/runs/detect/train/weights/best.pt")